version: '3'
services:
  mysql:
    container_name: flyway-database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flyway
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql