spring:
  datasource:
    url: jdbc:h2:file:./flyway;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=MySQL;DATABASE_TO_UPPER=false;
    username: root
    password: password
  jpa.hibernate.ddl-auto: none
  flyway.locations: classpath:db/migration
