spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:./flyway;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=MySQL;DATABASE_TO_UPPER=false;}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    repair: true
